# coding: utf-8

"""
    REMESITA API REST

    Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2004_items import InlineResponse2004Items  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2004Items(unittest.TestCase):
    """InlineResponse2004Items unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004Items(self):
        """Test InlineResponse2004Items"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2004_items.InlineResponse2004Items()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
