# coding: utf-8

"""
    REMESITA API REST

    Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.business_api import BusinessApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBusinessApi(unittest.TestCase):
    """BusinessApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.business_api.BusinessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rest_v1_business_get(self):
        """Test case for rest_v1_business_get

        Obtiene la lista de negocios registrados  # noqa: E501
        """
        pass

    def test_rest_v1_payment_link_post(self):
        """Test case for rest_v1_payment_link_post

        Genera un link de pago  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
