# coding: utf-8

"""
    REMESITA API REST

    Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.prepaid_cards_api import PrepaidCardsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPrepaidCardsApi(unittest.TestCase):
    """PrepaidCardsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.prepaid_cards_api.PrepaidCardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rest_v1_card_number_toggle_post(self):
        """Test case for rest_v1_card_number_toggle_post

        Bloquea o desbloquea una tarjeta  # noqa: E501
        """
        pass

    def test_rest_v1_card_number_transactions_pg_pg_size_get(self):
        """Test case for rest_v1_card_number_transactions_pg_pg_size_get

        Obtiene las transacciones de una tarjeta  # noqa: E501
        """
        pass

    def test_rest_v1_card_transfer_between_post(self):
        """Test case for rest_v1_card_transfer_between_post

        Transfiere saldo entre cuentas Remesita  # noqa: E501
        """
        pass

    def test_rest_v1_cards_get(self):
        """Test case for rest_v1_cards_get

        Obtiene la lista de tarjetas prepagadas  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
