# coding: utf-8

"""
    REMESITA API REST

    Api de remesita.com para desarrolladores. Primero obten tu apiKey y apiSecret, y para autenticarte debes ejecutar el endpoint rest/v1/auth en la respuesta obtendrás un token de acceso que debes usar en el resto de peticiones  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class InlineResponse2001(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'error': 'str',
        'tid': 'str'
    }

    attribute_map = {
        'success': 'success',
        'error': 'error',
        'tid': 'tid'
    }

    def __init__(self, success=None, error=None, tid=None, _configuration=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._success = None
        self._error = None
        self._tid = None
        self.discriminator = None

        if success is not None:
            self.success = success
        if error is not None:
            self.error = error
        if tid is not None:
            self.tid = tid

    @property
    def success(self):
        """Gets the success of this InlineResponse2001.  # noqa: E501

        Indica si la transferencia fue exitosa  # noqa: E501

        :return: The success of this InlineResponse2001.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this InlineResponse2001.

        Indica si la transferencia fue exitosa  # noqa: E501

        :param success: The success of this InlineResponse2001.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def error(self):
        """Gets the error of this InlineResponse2001.  # noqa: E501

        Mensaje de error en caso de fallo  # noqa: E501

        :return: The error of this InlineResponse2001.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this InlineResponse2001.

        Mensaje de error en caso de fallo  # noqa: E501

        :param error: The error of this InlineResponse2001.  # noqa: E501
        :type: str
        """

        self._error = error

    @property
    def tid(self):
        """Gets the tid of this InlineResponse2001.  # noqa: E501

        ID de la transacción en caso de éxito  # noqa: E501

        :return: The tid of this InlineResponse2001.  # noqa: E501
        :rtype: str
        """
        return self._tid

    @tid.setter
    def tid(self, tid):
        """Sets the tid of this InlineResponse2001.

        ID de la transacción en caso de éxito  # noqa: E501

        :param tid: The tid of this InlineResponse2001.  # noqa: E501
        :type: str
        """

        self._tid = tid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2001):
            return True

        return self.to_dict() != other.to_dict()
